#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


###### ADDED-BY-USER ######

# launch polybar
bash ~/.config/polybar/launch.sh --forest

# border color
bspc config normal_border_color "#4c566a"
bspc config focused_border_color "#05B5DD"
bspc config presel_feedback_color "#05B5DD"
